README.md
Added Devoxx with information that can be found here: https://devoxx.be/faq/
=> Devoxx, 2017.11.06-10 - Antwerp, Belgium

README.md
Hack.lu (@hack_lu #hacklu) - 2017.10.17-19 - Luxembourg, Luxembourg.
=> Hack.lu (@hack_lu #hacklu) - 2017.10.17-19 - Luxembourg, Luxembourg.

README.md
BSdiesLuxembourg (@BSidesLux #BSdiesLuxembourg) - 2017.10.20 - Luxembourg, Luxembourg.
=> BSdiesLuxembourg (@BSidesLux #BSdiesLuxembourg) - 2017.10.20 - Luxembourg, Luxembourg.

README.md
=> Mobilization (@mobilizationpl #Mobilization2017) - 2017.10.21 - Łódź, Poland

README.md
Developer conference in Berlin, Feb 23 2018
=> Added BOB 2018

README.md
I add the event Women Techmakers Montreal Celebrating International Women's Day. 
It's a tech conference who empower women in tech but it's open to everyone.
=> ADD Women Techmakers Montreal CFP

README.md
The link to ScalaSphere's C4P was outdated. I've also added more keywords.
=> Add DataSphere and ReactSphere and correct ScalaSphere info

README.md
TechSummit Berlin (@TechSummitIO #techsummitio)- 2018.04-12 - Berlin, Germany
=> TechSummit Berlin (@TechSummitIO #techsummitio)- 2018.04-12 - Berlin, Germany

README.md
Heisenbug Piter May 2018 , 17-18, Russia, Saint-Petersburg
=> Heisenbug Conference added

README.md
Reverts softwaremill/it-cfp-list#48
=> Revert "Scala Up North (@ScalaUpNorth #ScalaUpNorth) - 2018.09.28-29 - Toronto, Canada"

README.md
as per https://twitter.com/devconfza/status/1021651444766793728 the closing date for applications is the 31st August
=> DevConf.za: Amended closing date 

README.md
=> ConFrontJS 2018 (@confrontjs #confrontjs) - 2018.10.29 - Warsaw, Poland

README.md
=> Red Hat Summit

README.md
=> added codemotion conference

README.md
Updated dates and place for ngVikings 2019
=> chore: update ngVikings for 2019

README.md
Spring is coming, new events are arriving
=> March 2019 update

README.md
IT NonStop: J-Santa conference CFP
=> IT NonStop: J-Santa conference

README.md
=> Fixing minor typo on PyData Warsaw Conference 2019

README.md
Added CfP entry for the Build IT Right Conference in Newcastle Upon Tyne, UK.
=> Added Build IT Right 2020 conference.

README.md
GreenfieldConf.pl (@Greenfield_Conf #GreenfieldConf) - 2020.05.30 - Zielona Góra, Poland
Web: https://GreenfieldConf.pl
Date: 30 maj, 2020
Venue: Zielona Góra, Lubusz, Poland
YouTube: https://www.youtube.com/channel/UChG7hsrjUYyYG13AkSIfQIw/videos
Twitter: https://twitter.com/Greenfield_Conf
=> GreenfieldConf.pl - 2020.05.30 - Zielona Góra, Poland

README.md
=> GR8Conf and JDK IO (@gr8conf #gr8conf) - 2020.06.02-04 - Copenhagen, Denmark

README.md
CFP of Codemotion Madrid, it will end at 2020.03.20
=> Codemotion Madrid - (@CodemoMadrid #CodemotionMadrid20) - 2020.09.24-25 - Madrid, Spain

README.md
=> Spring I/O (@spring_io #springio20) - 2019.05.14-15 - Barcelona, Spain

README.md
=> <DataXDay> (@dataxday #dataxday) - <2020.06.17-17> - <Paris>, <France>

README.md
JavaZone 2020 (@JavaZone #javazone) - 2020.09.09-10 - Oslo, Norway
=> JavaZone 2020 (@JavaZone #javazone) - 2020.09.09-10 - Oslo, Norway

README.md
Please add ReactiveConf 2020 into the list. Thank you!
=> ReactiveConf 2020 (@ReactiveConf #GoReactive) - 2020.10.12-13 - Prague, Czech Republic
